package pl.sperka.ae2.plugin.oldclasses.convert;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CzestotOkres.java
 *
 * Created on 2011-05-31, 16:06:45
 */

import java.awt.*;

/**
 *
 * @author kapitan
 */
public class CzestotOkres extends javax.swing.JFrame {

    /** Creates new form CzestotOkres */
    public CzestotOkres( Component parent ) {
        initComponents();
        setLocationRelativeTo( parent );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbCzestotliwosc = new javax.swing.JRadioButton();
        rbOkres = new javax.swing.JRadioButton();
        txtCzestotliwosc = new javax.swing.JTextField();
        txtOkres = new javax.swing.JTextField();
        cbCzestotliwosc = new javax.swing.JComboBox();
        cbOkres = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Częstotliwość <=> Okres");
        setResizable(false);

        buttonGroup1.add(rbCzestotliwosc);
        rbCzestotliwosc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbCzestotliwosc.setSelected(true);
        rbCzestotliwosc.setLabel("Częstotliwość");
        rbCzestotliwosc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbCzestotliwoscMouseClicked(evt);
            }
        });

        buttonGroup1.add(rbOkres);
        rbOkres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbOkres.setLabel("Okres");
        rbOkres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbOkresMouseClicked(evt);
            }
        });

        txtCzestotliwosc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCzestotliwosc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCzestotliwoscKeyReleased(evt);
            }
        });

        txtOkres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtOkres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOkresKeyReleased(evt);
            }
        });

        cbCzestotliwosc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbCzestotliwosc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hz", "kHz", "MHz", "GHz" }));
        cbCzestotliwosc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCzestotliwoscItemStateChanged(evt);
            }
        });

        cbOkres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbOkres.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ms", "us", "ns", "ps" }));
        cbOkres.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbOkresItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbOkres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtOkres))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbCzestotliwosc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCzestotliwosc, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbCzestotliwosc, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbOkres, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCzestotliwosc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCzestotliwosc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCzestotliwosc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOkres, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbOkres, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbOkres, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int lock=0;
    private void rbCzestotliwoscMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbCzestotliwoscMouseClicked
        licz();
    }//GEN-LAST:event_rbCzestotliwoscMouseClicked

    private void rbOkresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbOkresMouseClicked
        licz();
    }//GEN-LAST:event_rbOkresMouseClicked

    private void txtCzestotliwoscKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCzestotliwoscKeyReleased
        licz();
    }//GEN-LAST:event_txtCzestotliwoscKeyReleased

    private void txtOkresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOkresKeyReleased
        licz();
    }//GEN-LAST:event_txtOkresKeyReleased

    private void cbCzestotliwoscItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCzestotliwoscItemStateChanged
        if (lock==0) licz();
    }//GEN-LAST:event_cbCzestotliwoscItemStateChanged

    private void cbOkresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbOkresItemStateChanged
        if (lock==0) licz();
    }//GEN-LAST:event_cbOkresItemStateChanged
    private void licz()
    {
        java.text.NumberFormat nf = java.text.NumberFormat.getInstance();
        float freq=0, period=0;
        if(rbCzestotliwosc.isSelected())
        {
            if(!txtCzestotliwosc.getText().equals(""))
            {
                try{
                freq=nf.parse(txtCzestotliwosc.getText()).floatValue();
                //if(cbCzestotliwosc.getSelectedItem().toString().equals("kHz")) freq*=1000;
                //if(cbCzestotliwosc.getSelectedItem().toString().equals("MHz")) freq*=1000000;
                //if(cbCzestotliwosc.getSelectedItem().toString().equals("GHz")) freq*=1000000000;
                period=1000/freq;
                lock=1;
                cbOkres.setSelectedIndex(cbCzestotliwosc.getSelectedIndex());
                /*if(period<1&&period>=0.001) {
                    period*=1000;
                    cbOkres.setSelectedIndex(1);
                }
                else if(period < 0.001 && period >= 0.000001) {
                    period *= 1000000;
                    cbOkres.setSelectedIndex(2);
                }
                else if(period < 0.000001) {
                    period *= 1000000000;
                    cbOkres.setSelectedIndex(3);
                }*/
                txtOkres.setText(nf.format(period));
                lock=0;
                } catch(Exception e) {}
            }
        }

        if(rbOkres.isSelected())
        {
            if(!txtOkres.getText().equals(""))
            {
                try{
                period=nf.parse(txtOkres.getText()).floatValue();
                /*if(cbOkres.getSelectedItem().toString().equals("ms")) period/=1000;
                if(cbOkres.getSelectedItem().toString().equals("ns")) period/=1000000;
                if(cbOkres.getSelectedItem().toString().equals("ps")) period/=1000000000;*/
                freq=(1000/period);
                lock=1;
                cbCzestotliwosc.setSelectedIndex(cbOkres.getSelectedIndex());
                /*cbCzestotliwosc.setSelectedIndex(0);
                if(freq > 1000 && freq <= 1000000) {
                    freq /= 1000;
                    cbCzestotliwosc.setSelectedIndex(1);
                }
                else if(freq > 1000000 && freq <= 1000000000) {
                    freq /= 1000000;
                    cbCzestotliwosc.setSelectedIndex(2);
                }
                else if(freq > 1000000000) {
                    freq /= 1000000000;
                    cbCzestotliwosc.setSelectedIndex(3);
                }*/
                txtCzestotliwosc.setText(nf.format(freq));
                lock=0;
                } catch(Exception e) {}
            }
        }
    }
    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbCzestotliwosc;
    private javax.swing.JComboBox cbOkres;
    private javax.swing.JRadioButton rbCzestotliwosc;
    private javax.swing.JRadioButton rbOkres;
    private javax.swing.JTextField txtCzestotliwosc;
    private javax.swing.JTextField txtOkres;
    // End of variables declaration//GEN-END:variables

}
