package pl.sperka.ae2.plugin.oldclasses.convert;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MIL.java
 *
 * Created on 2011-06-02, 14:26:22
 */

import java.awt.*;

/**
 *
 * @author kapitan
 */
public class MIL extends javax.swing.JFrame {

    /** Creates new form MIL */
    public MIL( Component parent ) {
        initComponents();
        setLocationRelativeTo( parent );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMIL = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblWynik = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kod MIL");
        setResizable(false);

        txtMIL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMIL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMILKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Kod MIL:");

        lblWynik.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMIL, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblWynik))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMIL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWynik)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMILKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMILKeyReleased
        if(txtMIL.getText().length()==3) licz();
    }//GEN-LAST:event_txtMILKeyReleased
    private void licz()
    {
        java.text.NumberFormat nf = java.text.NumberFormat.getInstance();
        try {
        float wynik=0;
        String wynik_str;
        wynik=nf.parse(txtMIL.getText().substring(0, 2)).floatValue()*
              Double.valueOf(Math.pow(10, nf.parse(txtMIL.getText()
              .substring(2, 3)).intValue())).floatValue();
        if(wynik<1000)
        {
            wynik_str=nf.format(wynik);
            lblWynik.setText("<html>Rezystor: "+wynik_str+" Ohm<br>Kondensator: "+wynik_str
                    +" pF<br>Cewka: "+wynik_str+" uH</html>");
        } else if(wynik>=1000&&wynik<1000000)
        {
            wynik_str=nf.format(wynik/1000);
            lblWynik.setText("<html>Rezystor: "+wynik_str+" kOhm<br>Kondensator: "+wynik_str
                    +" nF<br>Cewka: "+wynik_str+" mH</html>");
        } else if(wynik>=1000000)
        {
            wynik_str=nf.format(wynik/1000000);
            lblWynik.setText("<html>Rezystor: "+wynik_str+" MOhm<br>Kondensator: "+wynik_str
                    +" uF<br>Cewka: "+wynik_str+" H</html>");
        }
        } catch(Exception e) {}
    }
    /**
    * @param args the command line arguments
    */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblWynik;
    private javax.swing.JTextField txtMIL;
    // End of variables declaration//GEN-END:variables

}
