package pl.sperka.ae2.plugin.oldclasses.convert;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WatDbm.java
 *
 * Created on 2011-06-02, 13:21:44
 */

import java.awt.*;

/**
 *
 * @author kapitan
 */
public class WatDbm extends javax.swing.JFrame {

    /** Creates new form WatDbm */
    public WatDbm( Component parent ) {
        initComponents();
        setLocationRelativeTo( parent );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtWat = new javax.swing.JTextField();
        txtdBm = new javax.swing.JTextField();
        cbWat = new javax.swing.JComboBox();
        jbdB = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Wat <-> dBm");
        setResizable(false);

        txtWat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtWat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtWatKeyReleased(evt);
            }
        });

        txtdBm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdBm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdBmKeyReleased(evt);
            }
        });

        cbWat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbWat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "mW", "W" }));
        cbWat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbWatItemStateChanged(evt);
            }
        });

        jbdB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbdB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "dBm", "dBW" }));
        jbdB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jbdBItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtdBm, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(txtWat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbWat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbdB, 0, 84, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbWat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtdBm, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jbdB, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int lock=0;
    private void txtWatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWatKeyReleased
        Licz(0);
    }//GEN-LAST:event_txtWatKeyReleased

    private void cbWatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbWatItemStateChanged
        if(lock==0) Licz(0);
    }//GEN-LAST:event_cbWatItemStateChanged

    private void txtdBmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdBmKeyReleased
        Licz(1);
    }//GEN-LAST:event_txtdBmKeyReleased

    private void jbdBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jbdBItemStateChanged
        if(lock==0) Licz(1);
    }//GEN-LAST:event_jbdBItemStateChanged

    /**
    * @param args the command line arguments
    */
    private void Licz(int mode)
    {
        float wat=0, dbm=0;
        java.text.NumberFormat nf = java.text.NumberFormat.getInstance();
        try {
        if(mode==0&&!txtWat.getText().equals("")) //W->dBm
        {
            wat=nf.parse(txtWat.getText()).floatValue();
            if(cbWat.getSelectedItem().toString().equals("mW")){ wat/=1000; lock=1; jbdB.setSelectedIndex(0); lock=0; } 
            else { lock=1; jbdB.setSelectedIndex(1); lock=0;}
            dbm=Double.valueOf(10*Math.log10(wat/0.001)).floatValue();
            if(jbdB.getSelectedItem().toString().equals("dBW")) dbm-=30;
            txtdBm.setText(nf.format(dbm));
        } else if(mode==1&&!txtdBm.getText().equals(""))
        {
            dbm=nf.parse(txtdBm.getText()).floatValue();
            if(jbdB.getSelectedItem().toString().equals("dBW")) dbm+=30;
            wat=Double.valueOf(0.001*Math.pow(10, dbm/10)).floatValue();
            if(wat>=1)
            {
                lock=1;
                cbWat.setSelectedIndex(1);
                txtWat.setText(nf.format(wat));
                lock=0;
            } else
            {
                lock=1;
                cbWat.setSelectedIndex(0);
                txtWat.setText(nf.format(wat*1000));
                lock=0;
            }
        }
        } catch(Exception e) {}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbWat;
    private javax.swing.JComboBox jbdB;
    private javax.swing.JTextField txtWat;
    private javax.swing.JTextField txtdBm;
    // End of variables declaration//GEN-END:variables

}
