package pl.sperka.ae2.plugin.oldclasses.calculate;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Rad.java
 *
 * Created on 2011-04-22, 22:59:28
 */

import java.awt.*;

/**
 *
 * @author kapitan
 */
public class Radiator extends javax.swing.JFrame {

    /** Creates new form Rad */
    public Radiator( Component parent ) {
        initComponents();
        setLocationRelativeTo( parent );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtRezRad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbTempUkl = new javax.swing.JRadioButton();
        rbRezTerm = new javax.swing.JRadioButton();
        txtTempOt = new javax.swing.JTextField();
        txtTempUkl = new javax.swing.JTextField();
        txtMoc = new javax.swing.JTextField();
        txtRezOb = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Parametry radiatora");
        setResizable(false);

        txtRezRad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRezRad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRezRadKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Rezystancja termiczna radiatora (Rrhra) [K/W]:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Rezystancja term. obudowy układu (Rthj-c) [K/W]:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Moc wydzielana [W]:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Temp. układu [*C]:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Temp. otoczenia [*C]:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Wylicz"));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        buttonGroup1.add(rbTempUkl);
        rbTempUkl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbTempUkl.setText("Temp. chłodzonego układu");
        rbTempUkl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbTempUklMouseClicked(evt);
            }
        });

        buttonGroup1.add(rbRezTerm);
        rbRezTerm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbRezTerm.setSelected(true);
        rbRezTerm.setText("Rezystancję termiczną radiatora");
        rbRezTerm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbRezTermMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbTempUkl)
                    .addComponent(rbRezTerm))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rbRezTerm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbTempUkl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtTempOt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTempOt.setText("20");
        txtTempOt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTempOtKeyReleased(evt);
            }
        });

        txtTempUkl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTempUkl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTempUklKeyReleased(evt);
            }
        });

        txtMoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMocKeyReleased(evt);
            }
        });

        txtRezOb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRezOb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRezObKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTempUkl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTempOt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMoc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(txtRezOb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(txtRezRad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTempOt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTempUkl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMoc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRezOb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRezRad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRezRadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRezRadKeyReleased
        Licz();
}//GEN-LAST:event_txtRezRadKeyReleased

    private void rbRezTermMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbRezTermMouseClicked
        Licz();
}//GEN-LAST:event_rbRezTermMouseClicked

    private void rbTempUklMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbTempUklMouseClicked
        Licz();
}//GEN-LAST:event_rbTempUklMouseClicked

    private void txtTempOtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTempOtKeyReleased
        Licz();
}//GEN-LAST:event_txtTempOtKeyReleased

    private void txtTempUklKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTempUklKeyReleased
        Licz();
}//GEN-LAST:event_txtTempUklKeyReleased

    private void txtMocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMocKeyReleased
        Licz();
}//GEN-LAST:event_txtMocKeyReleased

    private void txtRezObKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRezObKeyReleased
        Licz();
}//GEN-LAST:event_txtRezObKeyReleased
private void Licz()
    {
        float TempUkl=0, TempOt=0, Moc=0, RezOb=0, RezRad=0;
        java.text.NumberFormat nf = java.text.NumberFormat.getInstance();
        try {
        if(rbRezTerm.isSelected())
        {
            if(!txtTempUkl.getText().equals("")&&!txtMoc.getText().equals("")&&!txtTempOt.getText().equals("")&&!txtRezOb.getText().equals(""))
            {
                TempUkl = nf.parse(txtTempUkl.getText()).floatValue();
                TempOt = nf.parse(txtTempOt.getText()).floatValue();
                Moc = nf.parse(txtMoc.getText()).floatValue();
                RezOb = nf.parse(txtRezOb.getText()).floatValue();

                RezRad = (TempUkl-TempOt)/Moc-RezOb;
                txtRezRad.setText(nf.format(RezRad));
            }
        }
        if(rbTempUkl.isSelected())
        {
            if(!txtRezRad.getText().equals("")&&!txtMoc.getText().equals("")&&!txtTempOt.getText().equals("")&&!txtRezRad.getText().equals(""))
            {
                RezRad = nf.parse(txtRezRad.getText()).floatValue();
                TempOt = nf.parse(txtTempOt.getText()).floatValue();
                Moc = nf.parse(txtMoc.getText()).floatValue();
                RezOb = nf.parse(txtRezOb.getText()).floatValue();

                TempUkl = Moc*(RezOb+RezRad)+TempOt;
                txtTempUkl.setText(nf.format(TempUkl));
            }
        }
        } catch(Exception e) {}
    }
    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbRezTerm;
    private javax.swing.JRadioButton rbTempUkl;
    private javax.swing.JTextField txtMoc;
    private javax.swing.JTextField txtRezOb;
    private javax.swing.JTextField txtRezRad;
    private javax.swing.JTextField txtTempOt;
    private javax.swing.JTextField txtTempUkl;
    // End of variables declaration//GEN-END:variables

}
