package pl.sperka.ae2.plugin.oldclasses.calculate;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RezystorLED.java
 *
 * Created on 2011-03-20, 13:41:53
 */

import java.awt.*;

/**
 *
 * @author Piotr Sperka
 */
public class RezystorLED extends javax.swing.JFrame {

    /** Creates new form RezystorLED */
    public RezystorLED( Component parent ) {
        initComponents();
        setLocationRelativeTo( parent );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUzas = new javax.swing.JTextField();
        txtUled = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIled = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblRez = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlRed = new javax.swing.JLabel();
        jlGreen = new javax.swing.JLabel();
        jlBlue = new javax.swing.JLabel();
        jlWhite = new javax.swing.JLabel();
        jlYellow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rezystor dla diody LED");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Napięcie zasilania [V]:");

        txtUzas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUzas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUzasKeyReleased(evt);
            }
        });

        txtUled.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUled.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUledKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nap. pracy diody [V]:");

        txtIled.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIled.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIledKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Prąd pracy diody [mA]:");

        lblRez.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Napięcia LED")));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jlRed.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlRed.setForeground(new java.awt.Color(255, 0, 0));
        jlRed.setText("Czerwona: 1,8V");
        jlRed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlRed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlRedMouseReleased(evt);
            }
        });

        jlGreen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlGreen.setForeground(new java.awt.Color(0, 204, 0));
        jlGreen.setText("Zielona: 2,0V");
        jlGreen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlGreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlGreenMouseReleased(evt);
            }
        });

        jlBlue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlBlue.setForeground(new java.awt.Color(0, 0, 255));
        jlBlue.setText("Niebieska: 3,5V");
        jlBlue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlBlue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlBlueMouseReleased(evt);
            }
        });

        jlWhite.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlWhite.setText("Biała: 3,6V");
        jlWhite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlWhite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlWhiteMouseReleased(evt);
            }
        });

        jlYellow.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlYellow.setForeground(new java.awt.Color(204, 204, 0));
        jlYellow.setText("Żółta: 1,8V");
        jlYellow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jlYellowMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlWhite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlBlue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlGreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlRed, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlYellow)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jlRed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlYellow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlGreen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlBlue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlWhite)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtIled, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(txtUled, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(txtUzas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)))
                    .addComponent(lblRez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUzas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUled, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIled, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRez)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIledKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIledKeyReleased
        Licz();
    }//GEN-LAST:event_txtIledKeyReleased

    private void txtUledKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUledKeyReleased
        Licz();
    }//GEN-LAST:event_txtUledKeyReleased

    private void txtUzasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUzasKeyReleased
        Licz();
    }//GEN-LAST:event_txtUzasKeyReleased

    private void jlRedMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlRedMouseReleased
        txtUled.setText("1,8");
        Licz();
    }//GEN-LAST:event_jlRedMouseReleased

    private void jlYellowMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlYellowMouseReleased
        txtUled.setText("1,8");
        Licz();
    }//GEN-LAST:event_jlYellowMouseReleased

    private void jlGreenMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlGreenMouseReleased
        txtUled.setText("2,0");
        Licz();
    }//GEN-LAST:event_jlGreenMouseReleased

    private void jlBlueMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBlueMouseReleased
        txtUled.setText("3,5");
        Licz();
    }//GEN-LAST:event_jlBlueMouseReleased

    private void jlWhiteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlWhiteMouseReleased
        txtUled.setText("3,6");
        Licz();
    }//GEN-LAST:event_jlWhiteMouseReleased
    private void Licz() {
        if((!txtUled.getText().equals(""))&&(!txtIled.getText().equals(""))&&(!txtUzas.getText().equals(""))){
            float Uled=0, Iled=0, Uzas=0, R=0, Prez=0;
            java.text.NumberFormat nf = java.text.NumberFormat.getInstance();
            try{
            Uled=nf.parse(txtUled.getText()).floatValue();
            Iled=(nf.parse(txtIled.getText()).floatValue())/1000;
            Uzas=nf.parse(txtUzas.getText()).floatValue();
            } catch(Exception e) {}
            R=(Uzas-Uled)/Iled;
            Prez=R*Iled*Iled*100;
            Prez=Math.round(Prez);
            R=Math.round(R*10);
            if(R<0) {
                lblRez.setText("Uzas < Uled !");
            } else  if((R<10000)&&(R>=0)) {
                lblRez.setText("Rezystor: "+nf.format(R/10)+" Ohm/"+nf.format(Prez/100)+" W");
            } else if((R>=10000)&&(R<10000000)) {
                lblRez.setText("Rezystor: "+nf.format(R/10000)+" kOhm/"+nf.format(Prez/100)+" W");
            } else if(R>=10000000) {
                lblRez.setText("Rezystor: "+nf.format(R/10000000)+" MOhm/"+nf.format(Prez/100)+" W");
            }
        }
    }

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RezystorLED().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlBlue;
    private javax.swing.JLabel jlGreen;
    private javax.swing.JLabel jlRed;
    private javax.swing.JLabel jlWhite;
    private javax.swing.JLabel jlYellow;
    private javax.swing.JLabel lblRez;
    private javax.swing.JTextField txtIled;
    private javax.swing.JTextField txtUled;
    private javax.swing.JTextField txtUzas;
    // End of variables declaration//GEN-END:variables

}
