package pl.sperka.ae2.plugin.oldclasses.calculate;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RezZast.java
 *
 * Created on 2011-07-17, 13:11:05
 */

import java.awt.*;

/**
 *
 * @author kapitan
 */
public class RezZast extends javax.swing.JFrame {

    /** Creates new form RezZast */
    public RezZast( Component parent ) {
        initComponents();
        rbSzer2MouseClicked(null);
        rbRown2MouseClicked(null);
        setLocationRelativeTo( parent );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void LiczRown()
    {
        double wynik=0,r1,r2,r3,r4,r5,r6,r7,r8,r9,r10;
        java.text.NumberFormat nf = java.text.NumberFormat.getInstance();
        try {
        if(rbRown2.isSelected())
        {
            r1=nf.parse(txtRown1.getText()).doubleValue();
            r2=nf.parse(txtRown2.getText()).doubleValue();
            if(r1==0||r2==0)wynik=0; else wynik=1/((1/r1)+(1/r2));
        }
        else if(rbRown3.isSelected())
        {
            r1=nf.parse(txtRown1.getText()).doubleValue();
            r2=nf.parse(txtRown2.getText()).doubleValue();
            r3=nf.parse(txtRown3.getText()).doubleValue();
            if(r1==0||r2==0||r3==0)wynik=0; else wynik=1/((1/r1)+(1/r2)+(1/r3));
        }
        else if(rbRown4.isSelected())
        {
            r1=nf.parse(txtRown1.getText()).doubleValue();
            r2=nf.parse(txtRown2.getText()).doubleValue();
            r3=nf.parse(txtRown3.getText()).doubleValue();
            r4=nf.parse(txtRown4.getText()).doubleValue();
            if(r1==0||r2==0||r3==0||r4==0)wynik=0; else wynik=1/((1/r1)+(1/r2)+(1/r3)+(1/r4));
        }
        else if(rbRown5.isSelected())
        {
            r1=nf.parse(txtRown1.getText()).doubleValue();
            r2=nf.parse(txtRown2.getText()).doubleValue();
            r3=nf.parse(txtRown3.getText()).doubleValue();
            r4=nf.parse(txtRown4.getText()).doubleValue();
            r5=nf.parse(txtRown5.getText()).doubleValue();
            if(r1==0||r2==0||r3==0||r4==0||r5==0)wynik=0;
            else wynik=1/((1/r1)+(1/r2)+(1/r3)+(1/r4)+(1/r5));
        }
        else if(rbRown6.isSelected())
        {
            r1=nf.parse(txtRown1.getText()).doubleValue();
            r2=nf.parse(txtRown2.getText()).doubleValue();
            r3=nf.parse(txtRown3.getText()).doubleValue();
            r4=nf.parse(txtRown4.getText()).doubleValue();
            r5=nf.parse(txtRown5.getText()).doubleValue();
            r6=nf.parse(txtRown6.getText()).doubleValue();
            if(r1==0||r2==0||r3==0||r4==0||r5==0||r6==0)wynik=0;
            else wynik=1/((1/r1)+(1/r2)+(1/r3)+(1/r4)+(1/r5)+(1/r6));
        }
        else if(rbRown7.isSelected())
        {
            r1=nf.parse(txtRown1.getText()).doubleValue();
            r2=nf.parse(txtRown2.getText()).doubleValue();
            r3=nf.parse(txtRown3.getText()).doubleValue();
            r4=nf.parse(txtRown4.getText()).doubleValue();
            r5=nf.parse(txtRown5.getText()).doubleValue();
            r6=nf.parse(txtRown6.getText()).doubleValue();
            r7=nf.parse(txtRown7.getText()).doubleValue();
            if(r1==0||r2==0||r3==0||r4==0||r5==0||r6==0||r7==0)wynik=0;
            else wynik=1/((1/r1)+(1/r2)+(1/r3)+(1/r4)+(1/r5)+(1/r6)+(1/r7));
        }
        else if(rbRown8.isSelected())
        {
            r1=nf.parse(txtRown1.getText()).doubleValue();
            r2=nf.parse(txtRown2.getText()).doubleValue();
            r3=nf.parse(txtRown3.getText()).doubleValue();
            r4=nf.parse(txtRown4.getText()).doubleValue();
            r5=nf.parse(txtRown5.getText()).doubleValue();
            r6=nf.parse(txtRown6.getText()).doubleValue();
            r7=nf.parse(txtRown7.getText()).doubleValue();
            r8=nf.parse(txtRown8.getText()).doubleValue();
            if(r1==0||r2==0||r3==0||r4==0||r5==0||r6==0||r7==0||r8==0)wynik=0;
            else wynik=1/((1/r1)+(1/r2)+(1/r3)+(1/r4)+(1/r5)+(1/r6)+(1/r7)+(1/r8));
        }
        else if(rbRown9.isSelected())
        {
            r1=nf.parse(txtRown1.getText()).doubleValue();
            r2=nf.parse(txtRown2.getText()).doubleValue();
            r3=nf.parse(txtRown3.getText()).doubleValue();
            r4=nf.parse(txtRown4.getText()).doubleValue();
            r5=nf.parse(txtRown5.getText()).doubleValue();
            r6=nf.parse(txtRown6.getText()).doubleValue();
            r7=nf.parse(txtRown7.getText()).doubleValue();
            r8=nf.parse(txtRown8.getText()).doubleValue();
            r9=nf.parse(txtRown9.getText()).doubleValue();
            if(r1==0||r2==0||r3==0||r4==0||r5==0||r6==0||r7==0||r8==0||r9==0)wynik=0;
            else wynik=1/((1/r1)+(1/r2)+(1/r3)+(1/r4)+(1/r5)+(1/r6)+(1/r7)+(1/r8)+(1/r9));
        }
        else if(rbRown10.isSelected())
        {
            r1=nf.parse(txtRown1.getText()).doubleValue();
            r2=nf.parse(txtRown2.getText()).doubleValue();
            r3=nf.parse(txtRown3.getText()).doubleValue();
            r4=nf.parse(txtRown4.getText()).doubleValue();
            r5=nf.parse(txtRown5.getText()).doubleValue();
            r6=nf.parse(txtRown6.getText()).doubleValue();
            r7=nf.parse(txtRown7.getText()).doubleValue();
            r8=nf.parse(txtRown8.getText()).doubleValue();
            r9=nf.parse(txtRown9.getText()).doubleValue();
            r10=nf.parse(txtRown10.getText()).doubleValue();
            if(r1==0||r2==0||r3==0||r4==0||r5==0||r6==0||r7==0||r8==0||r9==0||r10==0)wynik=0;
            else wynik=1/((1/r1)+(1/r2)+(1/r3)+(1/r4)+(1/r5)+(1/r6)+(1/r7)+(1/r8)+(1/r9)+(1/r10));
        }
        lblRownWynik.setText("Wynik: "+nf.format(wynik)+" Ohm");
        } catch(Exception e) {}
    }
    
    private void Licz()
    {
        double wynik=0;
        java.text.NumberFormat nf = java.text.NumberFormat.getInstance();
        try {
        if(rbSzer2.isSelected()) wynik=nf.parse(txtSzer1.getText()).intValue()+nf.parse(txtSzer2.getText()).intValue();
        if(rbSzer3.isSelected()) wynik=nf.parse(txtSzer1.getText()).intValue()+nf.parse(txtSzer2.getText()).intValue()
                +nf.parse(txtSzer3.getText()).intValue();
        if(rbSzer4.isSelected()) wynik=nf.parse(txtSzer1.getText()).intValue()+nf.parse(txtSzer2.getText()).intValue()
                +nf.parse(txtSzer3.getText()).intValue()+nf.parse(txtSzer4.getText()).intValue();
        if(rbSzer5.isSelected()) wynik=nf.parse(txtSzer1.getText()).intValue()+nf.parse(txtSzer2.getText()).intValue()
                +nf.parse(txtSzer3.getText()).intValue()+nf.parse(txtSzer4.getText()).intValue()
                +nf.parse(txtSzer5.getText()).intValue();
        if(rbSzer6.isSelected()) wynik=nf.parse(txtSzer1.getText()).intValue()+nf.parse(txtSzer2.getText()).intValue()
                +nf.parse(txtSzer3.getText()).intValue()+nf.parse(txtSzer4.getText()).intValue()
                +nf.parse(txtSzer5.getText()).intValue()+nf.parse(txtSzer6.getText()).intValue();
        if(rbSzer7.isSelected()) wynik=nf.parse(txtSzer1.getText()).intValue()+nf.parse(txtSzer2.getText()).intValue()
                +nf.parse(txtSzer3.getText()).intValue()+nf.parse(txtSzer4.getText()).intValue()
                +nf.parse(txtSzer5.getText()).intValue()+nf.parse(txtSzer6.getText()).intValue()
                +nf.parse(txtSzer7.getText()).intValue();
        if(rbSzer8.isSelected()) wynik=nf.parse(txtSzer1.getText()).intValue()+nf.parse(txtSzer2.getText()).intValue()
                +nf.parse(txtSzer3.getText()).intValue()+nf.parse(txtSzer4.getText()).intValue()
                +nf.parse(txtSzer5.getText()).intValue()+nf.parse(txtSzer6.getText()).intValue()
                +nf.parse(txtSzer7.getText()).intValue()+nf.parse(txtSzer8.getText()).intValue();
        if(rbSzer9.isSelected()) wynik=nf.parse(txtSzer1.getText()).intValue()+nf.parse(txtSzer2.getText()).intValue()
                +nf.parse(txtSzer3.getText()).intValue()+nf.parse(txtSzer4.getText()).intValue()
                +nf.parse(txtSzer5.getText()).intValue()+nf.parse(txtSzer6.getText()).intValue()
                +nf.parse(txtSzer7.getText()).intValue()+nf.parse(txtSzer8.getText()).intValue()
                +nf.parse(txtSzer9.getText()).intValue();
        if(rbSzer10.isSelected()) wynik=nf.parse(txtSzer1.getText()).intValue()+nf.parse(txtSzer2.getText()).intValue()
                +nf.parse(txtSzer3.getText()).intValue()+nf.parse(txtSzer4.getText()).intValue()
                +nf.parse(txtSzer5.getText()).intValue()+nf.parse(txtSzer6.getText()).intValue()
                +nf.parse(txtSzer7.getText()).intValue()+nf.parse(txtSzer8.getText()).intValue()
                +nf.parse(txtSzer9.getText()).intValue()+nf.parse(txtSzer10.getText()).intValue();
        lblSzerWynik.setText("Wynik: "+nf.format(wynik)+" Ohm");
        } catch(Exception e) {}
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSzer1 = new javax.swing.JTextField();
        txtSzer2 = new javax.swing.JTextField();
        txtSzer3 = new javax.swing.JTextField();
        txtSzer4 = new javax.swing.JTextField();
        txtSzer5 = new javax.swing.JTextField();
        txtSzer6 = new javax.swing.JTextField();
        txtSzer7 = new javax.swing.JTextField();
        txtSzer8 = new javax.swing.JTextField();
        txtSzer9 = new javax.swing.JTextField();
        txtSzer10 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rbSzer2 = new javax.swing.JRadioButton();
        rbSzer3 = new javax.swing.JRadioButton();
        rbSzer4 = new javax.swing.JRadioButton();
        rbSzer5 = new javax.swing.JRadioButton();
        rbSzer6 = new javax.swing.JRadioButton();
        rbSzer7 = new javax.swing.JRadioButton();
        rbSzer8 = new javax.swing.JRadioButton();
        rbSzer9 = new javax.swing.JRadioButton();
        rbSzer10 = new javax.swing.JRadioButton();
        lblSzerWynik = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtRown10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtRown9 = new javax.swing.JTextField();
        txtRown8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtRown7 = new javax.swing.JTextField();
        txtRown6 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtRown5 = new javax.swing.JTextField();
        txtRown4 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtRown3 = new javax.swing.JTextField();
        txtRown2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtRown1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        rbRown2 = new javax.swing.JRadioButton();
        rbRown3 = new javax.swing.JRadioButton();
        rbRown4 = new javax.swing.JRadioButton();
        rbRown5 = new javax.swing.JRadioButton();
        rbRown6 = new javax.swing.JRadioButton();
        rbRown7 = new javax.swing.JRadioButton();
        rbRown8 = new javax.swing.JRadioButton();
        rbRown9 = new javax.swing.JRadioButton();
        rbRown10 = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        lblRownWynik = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rezystancja zastępcza");
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Rezystor 1");

        txtSzer1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSzer1.setText("0");
        txtSzer1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSzer1KeyReleased(evt);
            }
        });

        txtSzer2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSzer2.setText("0");
        txtSzer2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSzer2KeyReleased(evt);
            }
        });

        txtSzer3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSzer3.setText("0");
        txtSzer3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSzer3KeyReleased(evt);
            }
        });

        txtSzer4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSzer4.setText("0");
        txtSzer4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSzer4KeyReleased(evt);
            }
        });

        txtSzer5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSzer5.setText("0");
        txtSzer5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSzer5KeyReleased(evt);
            }
        });

        txtSzer6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSzer6.setText("0");
        txtSzer6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSzer6KeyReleased(evt);
            }
        });

        txtSzer7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSzer7.setText("0");
        txtSzer7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSzer7KeyReleased(evt);
            }
        });

        txtSzer8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSzer8.setText("0");
        txtSzer8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSzer8KeyReleased(evt);
            }
        });

        txtSzer9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSzer9.setText("0");
        txtSzer9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSzer9KeyReleased(evt);
            }
        });

        txtSzer10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSzer10.setText("0");
        txtSzer10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSzer10KeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Rezystor 2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Rezystor 3");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Rezystor 4");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Rezystor 5");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Rezystor 6");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Rezystor 7");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Rezystor 8");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Rezystor 9");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Rezystor 10");

        jLabel11.setFont(jLabel11.getFont().deriveFont(jLabel11.getFont().getStyle() | java.awt.Font.BOLD, 24));
        jLabel11.setText("Ohm");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ilość rezystorów"));
        jPanel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        buttonGroup1.add(rbSzer2);
        rbSzer2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbSzer2.setSelected(true);
        rbSzer2.setText("2");
        rbSzer2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbSzer2MouseClicked(evt);
            }
        });

        buttonGroup1.add(rbSzer3);
        rbSzer3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbSzer3.setText("3");
        rbSzer3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbSzer3MouseClicked(evt);
            }
        });

        buttonGroup1.add(rbSzer4);
        rbSzer4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbSzer4.setText("4");
        rbSzer4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbSzer4MouseClicked(evt);
            }
        });

        buttonGroup1.add(rbSzer5);
        rbSzer5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbSzer5.setText("5");
        rbSzer5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbSzer5MouseClicked(evt);
            }
        });

        buttonGroup1.add(rbSzer6);
        rbSzer6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbSzer6.setText("6");
        rbSzer6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbSzer6MouseClicked(evt);
            }
        });

        buttonGroup1.add(rbSzer7);
        rbSzer7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbSzer7.setText("7");
        rbSzer7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbSzer7MouseClicked(evt);
            }
        });

        buttonGroup1.add(rbSzer8);
        rbSzer8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbSzer8.setText("8");
        rbSzer8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbSzer8MouseClicked(evt);
            }
        });

        buttonGroup1.add(rbSzer9);
        rbSzer9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbSzer9.setText("9");
        rbSzer9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbSzer9MouseClicked(evt);
            }
        });

        buttonGroup1.add(rbSzer10);
        rbSzer10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbSzer10.setText("10");
        rbSzer10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbSzer10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbSzer6)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbSzer5)
                            .addComponent(rbSzer4)
                            .addComponent(rbSzer3)
                            .addComponent(rbSzer2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbSzer7)
                            .addComponent(rbSzer8)
                            .addComponent(rbSzer9)
                            .addComponent(rbSzer10))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSzer2)
                    .addComponent(rbSzer7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSzer3)
                    .addComponent(rbSzer8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSzer4)
                    .addComponent(rbSzer9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSzer5)
                    .addComponent(rbSzer10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbSzer6))
        );

        lblSzerWynik.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSzerWynik.setText("Wynik: 0 Ohm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSzer6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSzer4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSzer3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSzer2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSzer1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSzer7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSzer10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSzer9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSzer8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSzer5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSzerWynik))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSzerWynik))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSzer1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSzer2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSzer3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSzer4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSzer5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSzer6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSzer7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSzer8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSzer9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSzer10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Połączenie szeregowe", jPanel1);

        txtRown10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRown10.setText("0");
        txtRown10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRown10KeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Rezystor 10");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Rezystor 9");

        txtRown9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRown9.setText("0");
        txtRown9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRown9KeyReleased(evt);
            }
        });

        txtRown8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRown8.setText("0");
        txtRown8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRown8KeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Rezystor 8");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Rezystor 7");

        txtRown7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRown7.setText("0");
        txtRown7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRown7KeyReleased(evt);
            }
        });

        txtRown6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRown6.setText("0");
        txtRown6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRown6KeyReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Rezystor 6");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Rezystor 5");

        txtRown5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRown5.setText("0");
        txtRown5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRown5KeyReleased(evt);
            }
        });

        txtRown4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRown4.setText("0");
        txtRown4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRown4KeyReleased(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Rezystor 4");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Rezystor 3");

        txtRown3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRown3.setText("0");
        txtRown3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRown3KeyReleased(evt);
            }
        });

        txtRown2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRown2.setText("0");
        txtRown2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRown2KeyReleased(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Rezystor 2");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Rezystor 1");

        txtRown1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRown1.setText("0");
        txtRown1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRown1KeyReleased(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ilość rezystorów"));
        jPanel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        buttonGroup2.add(rbRown2);
        rbRown2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbRown2.setSelected(true);
        rbRown2.setText("2");
        rbRown2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbRown2MouseClicked(evt);
            }
        });

        buttonGroup2.add(rbRown3);
        rbRown3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbRown3.setText("3");
        rbRown3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbRown3MouseClicked(evt);
            }
        });

        buttonGroup2.add(rbRown4);
        rbRown4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbRown4.setText("4");
        rbRown4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbRown4MouseClicked(evt);
            }
        });

        buttonGroup2.add(rbRown5);
        rbRown5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbRown5.setText("5");
        rbRown5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbRown5MouseClicked(evt);
            }
        });

        buttonGroup2.add(rbRown6);
        rbRown6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbRown6.setText("6");
        rbRown6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbRown6MouseClicked(evt);
            }
        });

        buttonGroup2.add(rbRown7);
        rbRown7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbRown7.setText("7");
        rbRown7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbRown7MouseClicked(evt);
            }
        });

        buttonGroup2.add(rbRown8);
        rbRown8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbRown8.setText("8");
        rbRown8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbRown8MouseClicked(evt);
            }
        });

        buttonGroup2.add(rbRown9);
        rbRown9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbRown9.setText("9");
        rbRown9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbRown9MouseClicked(evt);
            }
        });

        buttonGroup2.add(rbRown10);
        rbRown10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbRown10.setText("10");
        rbRown10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbRown10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbRown6)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbRown5)
                            .addComponent(rbRown4)
                            .addComponent(rbRown3)
                            .addComponent(rbRown2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbRown7)
                            .addComponent(rbRown8)
                            .addComponent(rbRown9)
                            .addComponent(rbRown10))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbRown2)
                    .addComponent(rbRown7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbRown3)
                    .addComponent(rbRown8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbRown4)
                    .addComponent(rbRown9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbRown5)
                    .addComponent(rbRown10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbRown6))
        );

        jLabel22.setFont(jLabel22.getFont().deriveFont(jLabel22.getFont().getStyle() | java.awt.Font.BOLD, 24));
        jLabel22.setText("Ohm");

        lblRownWynik.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRownWynik.setText("Wynik: 0 Ohm");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRown6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtRown5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22))
                            .addComponent(txtRown4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRown3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRown2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRown1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRown7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRownWynik))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRown10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRown9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRown8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(321, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRownWynik))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRown1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRown2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRown3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRown4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRown5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRown6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRown7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRown8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRown9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRown10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Połączenie równoległe", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbSzer2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbSzer2MouseClicked
        jLabel1.setVisible(true); txtSzer1.setVisible(true);
        jLabel2.setVisible(true); txtSzer2.setVisible(true);
        jLabel3.setVisible(false); txtSzer3.setVisible(false);
        jLabel4.setVisible(false); txtSzer4.setVisible(false);
        jLabel5.setVisible(false); txtSzer5.setVisible(false);
        jLabel6.setVisible(false); txtSzer6.setVisible(false);
        jLabel7.setVisible(false); txtSzer7.setVisible(false);
        jLabel8.setVisible(false); txtSzer8.setVisible(false);
        jLabel9.setVisible(false); txtSzer9.setVisible(false);
        jLabel10.setVisible(false); txtSzer10.setVisible(false);
        Licz();
    }//GEN-LAST:event_rbSzer2MouseClicked

    private void rbSzer3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbSzer3MouseClicked
        jLabel1.setVisible(true); txtSzer1.setVisible(true);
        jLabel2.setVisible(true); txtSzer2.setVisible(true);
        jLabel3.setVisible(true); txtSzer3.setVisible(true);
        jLabel4.setVisible(false); txtSzer4.setVisible(false);
        jLabel5.setVisible(false); txtSzer5.setVisible(false);
        jLabel6.setVisible(false); txtSzer6.setVisible(false);
        jLabel7.setVisible(false); txtSzer7.setVisible(false);
        jLabel8.setVisible(false); txtSzer8.setVisible(false);
        jLabel9.setVisible(false); txtSzer9.setVisible(false);
        jLabel10.setVisible(false); txtSzer10.setVisible(false);
        Licz();
    }//GEN-LAST:event_rbSzer3MouseClicked

    private void rbSzer4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbSzer4MouseClicked
        jLabel1.setVisible(true); txtSzer1.setVisible(true);
        jLabel2.setVisible(true); txtSzer2.setVisible(true);
        jLabel3.setVisible(true); txtSzer3.setVisible(true);
        jLabel4.setVisible(true); txtSzer4.setVisible(true);
        jLabel5.setVisible(false); txtSzer5.setVisible(false);
        jLabel6.setVisible(false); txtSzer6.setVisible(false);
        jLabel7.setVisible(false); txtSzer7.setVisible(false);
        jLabel8.setVisible(false); txtSzer8.setVisible(false);
        jLabel9.setVisible(false); txtSzer9.setVisible(false);
        jLabel10.setVisible(false); txtSzer10.setVisible(false);
        Licz();
    }//GEN-LAST:event_rbSzer4MouseClicked

    private void rbSzer5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbSzer5MouseClicked
        jLabel1.setVisible(true); txtSzer1.setVisible(true);
        jLabel2.setVisible(true); txtSzer2.setVisible(true);
        jLabel3.setVisible(true); txtSzer3.setVisible(true);
        jLabel4.setVisible(true); txtSzer4.setVisible(true);
        jLabel5.setVisible(true); txtSzer5.setVisible(true);
        jLabel6.setVisible(false); txtSzer6.setVisible(false);
        jLabel7.setVisible(false); txtSzer7.setVisible(false);
        jLabel8.setVisible(false); txtSzer8.setVisible(false);
        jLabel9.setVisible(false); txtSzer9.setVisible(false);
        jLabel10.setVisible(false); txtSzer10.setVisible(false);
        Licz();
    }//GEN-LAST:event_rbSzer5MouseClicked

    private void rbSzer6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbSzer6MouseClicked
        jLabel1.setVisible(true); txtSzer1.setVisible(true);
        jLabel2.setVisible(true); txtSzer2.setVisible(true);
        jLabel3.setVisible(true); txtSzer3.setVisible(true);
        jLabel4.setVisible(true); txtSzer4.setVisible(true);
        jLabel5.setVisible(true); txtSzer5.setVisible(true);
        jLabel6.setVisible(true); txtSzer6.setVisible(true);
        jLabel7.setVisible(false); txtSzer7.setVisible(false);
        jLabel8.setVisible(false); txtSzer8.setVisible(false);
        jLabel9.setVisible(false); txtSzer9.setVisible(false);
        jLabel10.setVisible(false); txtSzer10.setVisible(false);
        Licz();
    }//GEN-LAST:event_rbSzer6MouseClicked

    private void rbSzer7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbSzer7MouseClicked
        jLabel1.setVisible(true); txtSzer1.setVisible(true);
        jLabel2.setVisible(true); txtSzer2.setVisible(true);
        jLabel3.setVisible(true); txtSzer3.setVisible(true);
        jLabel4.setVisible(true); txtSzer4.setVisible(true);
        jLabel5.setVisible(true); txtSzer5.setVisible(true);
        jLabel6.setVisible(true); txtSzer6.setVisible(true);
        jLabel7.setVisible(true); txtSzer7.setVisible(true);
        jLabel8.setVisible(false); txtSzer8.setVisible(false);
        jLabel9.setVisible(false); txtSzer9.setVisible(false);
        jLabel10.setVisible(false); txtSzer10.setVisible(false);
        Licz();
    }//GEN-LAST:event_rbSzer7MouseClicked

    private void rbSzer8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbSzer8MouseClicked
        jLabel1.setVisible(true); txtSzer1.setVisible(true);
        jLabel2.setVisible(true); txtSzer2.setVisible(true);
        jLabel3.setVisible(true); txtSzer3.setVisible(true);
        jLabel4.setVisible(true); txtSzer4.setVisible(true);
        jLabel5.setVisible(true); txtSzer5.setVisible(true);
        jLabel6.setVisible(true); txtSzer6.setVisible(true);
        jLabel7.setVisible(true); txtSzer7.setVisible(true);
        jLabel8.setVisible(true); txtSzer8.setVisible(true);
        jLabel9.setVisible(false); txtSzer9.setVisible(false);
        jLabel10.setVisible(false); txtSzer10.setVisible(false);
        Licz();
    }//GEN-LAST:event_rbSzer8MouseClicked

    private void rbSzer9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbSzer9MouseClicked
        jLabel1.setVisible(true); txtSzer1.setVisible(true);
        jLabel2.setVisible(true); txtSzer2.setVisible(true);
        jLabel3.setVisible(true); txtSzer3.setVisible(true);
        jLabel4.setVisible(true); txtSzer4.setVisible(true);
        jLabel5.setVisible(true); txtSzer5.setVisible(true);
        jLabel6.setVisible(true); txtSzer6.setVisible(true);
        jLabel7.setVisible(true); txtSzer7.setVisible(true);
        jLabel8.setVisible(true); txtSzer8.setVisible(true);
        jLabel9.setVisible(true); txtSzer9.setVisible(true);
        jLabel10.setVisible(false); txtSzer10.setVisible(false);
        Licz();
    }//GEN-LAST:event_rbSzer9MouseClicked

    private void rbSzer10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbSzer10MouseClicked
        jLabel1.setVisible(true); txtSzer1.setVisible(true);
        jLabel2.setVisible(true); txtSzer2.setVisible(true);
        jLabel3.setVisible(true); txtSzer3.setVisible(true);
        jLabel4.setVisible(true); txtSzer4.setVisible(true);
        jLabel5.setVisible(true); txtSzer5.setVisible(true);
        jLabel6.setVisible(true); txtSzer6.setVisible(true);
        jLabel7.setVisible(true); txtSzer7.setVisible(true);
        jLabel8.setVisible(true); txtSzer8.setVisible(true);
        jLabel9.setVisible(true); txtSzer9.setVisible(true);
        jLabel10.setVisible(true); txtSzer10.setVisible(true);
        Licz();
    }//GEN-LAST:event_rbSzer10MouseClicked

    private void txtSzer1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSzer1KeyReleased
        Licz();
    }//GEN-LAST:event_txtSzer1KeyReleased

    private void txtSzer2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSzer2KeyReleased
        Licz();
    }//GEN-LAST:event_txtSzer2KeyReleased

    private void txtSzer3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSzer3KeyReleased
        Licz();
    }//GEN-LAST:event_txtSzer3KeyReleased

    private void txtSzer4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSzer4KeyReleased
        Licz();
    }//GEN-LAST:event_txtSzer4KeyReleased

    private void txtSzer5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSzer5KeyReleased
        Licz();
    }//GEN-LAST:event_txtSzer5KeyReleased

    private void txtSzer6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSzer6KeyReleased
        Licz();
    }//GEN-LAST:event_txtSzer6KeyReleased

    private void txtSzer7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSzer7KeyReleased
        Licz();
    }//GEN-LAST:event_txtSzer7KeyReleased

    private void txtSzer8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSzer8KeyReleased
        Licz();
    }//GEN-LAST:event_txtSzer8KeyReleased

    private void txtSzer9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSzer9KeyReleased
        Licz();
    }//GEN-LAST:event_txtSzer9KeyReleased

    private void txtSzer10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSzer10KeyReleased
        Licz();
    }//GEN-LAST:event_txtSzer10KeyReleased

    private void txtRown10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRown10KeyReleased
        LiczRown();
    }//GEN-LAST:event_txtRown10KeyReleased

    private void txtRown9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRown9KeyReleased
        LiczRown();
    }//GEN-LAST:event_txtRown9KeyReleased

    private void txtRown8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRown8KeyReleased
        LiczRown();
    }//GEN-LAST:event_txtRown8KeyReleased

    private void txtRown7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRown7KeyReleased
        LiczRown();
    }//GEN-LAST:event_txtRown7KeyReleased

    private void txtRown6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRown6KeyReleased
        LiczRown();
    }//GEN-LAST:event_txtRown6KeyReleased

    private void txtRown5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRown5KeyReleased
        LiczRown();
    }//GEN-LAST:event_txtRown5KeyReleased

    private void txtRown4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRown4KeyReleased
        LiczRown();
    }//GEN-LAST:event_txtRown4KeyReleased

    private void txtRown3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRown3KeyReleased
        LiczRown();
    }//GEN-LAST:event_txtRown3KeyReleased

    private void txtRown2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRown2KeyReleased
        LiczRown();
    }//GEN-LAST:event_txtRown2KeyReleased

    private void txtRown1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRown1KeyReleased
        LiczRown();
    }//GEN-LAST:event_txtRown1KeyReleased

    private void rbRown2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbRown2MouseClicked
        jLabel21.setVisible(true); txtRown1.setVisible(true);
        jLabel20.setVisible(true); txtRown2.setVisible(true);
        jLabel19.setVisible(false); txtRown3.setVisible(false);
        jLabel18.setVisible(false); txtRown4.setVisible(false);
        jLabel17.setVisible(false); txtRown5.setVisible(false);
        jLabel16.setVisible(false); txtRown6.setVisible(false);
        jLabel15.setVisible(false); txtRown7.setVisible(false);
        jLabel14.setVisible(false); txtRown8.setVisible(false);
        jLabel13.setVisible(false); txtRown9.setVisible(false);
        jLabel12.setVisible(false); txtRown10.setVisible(false);
        LiczRown();
    }//GEN-LAST:event_rbRown2MouseClicked

    private void rbRown3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbRown3MouseClicked
        jLabel21.setVisible(true); txtRown1.setVisible(true);
        jLabel20.setVisible(true); txtRown2.setVisible(true);
        jLabel19.setVisible(true); txtRown3.setVisible(true);
        jLabel18.setVisible(false); txtRown4.setVisible(false);
        jLabel17.setVisible(false); txtRown5.setVisible(false);
        jLabel16.setVisible(false); txtRown6.setVisible(false);
        jLabel15.setVisible(false); txtRown7.setVisible(false);
        jLabel14.setVisible(false); txtRown8.setVisible(false);
        jLabel13.setVisible(false); txtRown9.setVisible(false);
        jLabel12.setVisible(false); txtRown10.setVisible(false);
        LiczRown();
    }//GEN-LAST:event_rbRown3MouseClicked

    private void rbRown4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbRown4MouseClicked
        jLabel21.setVisible(true); txtRown1.setVisible(true);
        jLabel20.setVisible(true); txtRown2.setVisible(true);
        jLabel19.setVisible(true); txtRown3.setVisible(true);
        jLabel18.setVisible(true); txtRown4.setVisible(true);
        jLabel17.setVisible(false); txtRown5.setVisible(false);
        jLabel16.setVisible(false); txtRown6.setVisible(false);
        jLabel15.setVisible(false); txtRown7.setVisible(false);
        jLabel14.setVisible(false); txtRown8.setVisible(false);
        jLabel13.setVisible(false); txtRown9.setVisible(false);
        jLabel12.setVisible(false); txtRown10.setVisible(false);
        LiczRown();
    }//GEN-LAST:event_rbRown4MouseClicked

    private void rbRown5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbRown5MouseClicked
        jLabel21.setVisible(true); txtRown1.setVisible(true);
        jLabel20.setVisible(true); txtRown2.setVisible(true);
        jLabel19.setVisible(true); txtRown3.setVisible(true);
        jLabel18.setVisible(true); txtRown4.setVisible(true);
        jLabel17.setVisible(true); txtRown5.setVisible(true);
        jLabel16.setVisible(false); txtRown6.setVisible(false);
        jLabel15.setVisible(false); txtRown7.setVisible(false);
        jLabel14.setVisible(false); txtRown8.setVisible(false);
        jLabel13.setVisible(false); txtRown9.setVisible(false);
        jLabel12.setVisible(false); txtRown10.setVisible(false);
        LiczRown();
    }//GEN-LAST:event_rbRown5MouseClicked

    private void rbRown6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbRown6MouseClicked
        jLabel21.setVisible(true); txtRown1.setVisible(true);
        jLabel20.setVisible(true); txtRown2.setVisible(true);
        jLabel19.setVisible(true); txtRown3.setVisible(true);
        jLabel18.setVisible(true); txtRown4.setVisible(true);
        jLabel17.setVisible(true); txtRown5.setVisible(true);
        jLabel16.setVisible(true); txtRown6.setVisible(true);
        jLabel15.setVisible(false); txtRown7.setVisible(false);
        jLabel14.setVisible(false); txtRown8.setVisible(false);
        jLabel13.setVisible(false); txtRown9.setVisible(false);
        jLabel12.setVisible(false); txtRown10.setVisible(false);
        LiczRown();
    }//GEN-LAST:event_rbRown6MouseClicked

    private void rbRown7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbRown7MouseClicked
        jLabel21.setVisible(true); txtRown1.setVisible(true);
        jLabel20.setVisible(true); txtRown2.setVisible(true);
        jLabel19.setVisible(true); txtRown3.setVisible(true);
        jLabel18.setVisible(true); txtRown4.setVisible(true);
        jLabel17.setVisible(true); txtRown5.setVisible(true);
        jLabel16.setVisible(true); txtRown6.setVisible(true);
        jLabel15.setVisible(true); txtRown7.setVisible(true);
        jLabel14.setVisible(false); txtRown8.setVisible(false);
        jLabel13.setVisible(false); txtRown9.setVisible(false);
        jLabel12.setVisible(false); txtRown10.setVisible(false);
        LiczRown();
    }//GEN-LAST:event_rbRown7MouseClicked

    private void rbRown8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbRown8MouseClicked
        jLabel21.setVisible(true); txtRown1.setVisible(true);
        jLabel20.setVisible(true); txtRown2.setVisible(true);
        jLabel19.setVisible(true); txtRown3.setVisible(true);
        jLabel18.setVisible(true); txtRown4.setVisible(true);
        jLabel17.setVisible(true); txtRown5.setVisible(true);
        jLabel16.setVisible(true); txtRown6.setVisible(true);
        jLabel15.setVisible(true); txtRown7.setVisible(true);
        jLabel14.setVisible(true); txtRown8.setVisible(true);
        jLabel13.setVisible(false); txtRown9.setVisible(false);
        jLabel12.setVisible(false); txtRown10.setVisible(false);
        LiczRown();
    }//GEN-LAST:event_rbRown8MouseClicked

    private void rbRown9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbRown9MouseClicked
        jLabel21.setVisible(true); txtRown1.setVisible(true);
        jLabel20.setVisible(true); txtRown2.setVisible(true);
        jLabel19.setVisible(true); txtRown3.setVisible(true);
        jLabel18.setVisible(true); txtRown4.setVisible(true);
        jLabel17.setVisible(true); txtRown5.setVisible(true);
        jLabel16.setVisible(true); txtRown6.setVisible(true);
        jLabel15.setVisible(true); txtRown7.setVisible(true);
        jLabel14.setVisible(true); txtRown8.setVisible(true);
        jLabel13.setVisible(true); txtRown9.setVisible(true);
        jLabel12.setVisible(false); txtRown10.setVisible(false);
        LiczRown();
    }//GEN-LAST:event_rbRown9MouseClicked

    private void rbRown10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbRown10MouseClicked
        jLabel21.setVisible(true); txtRown1.setVisible(true);
        jLabel20.setVisible(true); txtRown2.setVisible(true);
        jLabel19.setVisible(true); txtRown3.setVisible(true);
        jLabel18.setVisible(true); txtRown4.setVisible(true);
        jLabel17.setVisible(true); txtRown5.setVisible(true);
        jLabel16.setVisible(true); txtRown6.setVisible(true);
        jLabel15.setVisible(true); txtRown7.setVisible(true);
        jLabel14.setVisible(true); txtRown8.setVisible(true);
        jLabel13.setVisible(true); txtRown9.setVisible(true);
        jLabel12.setVisible(true); txtRown10.setVisible(true);
        LiczRown();
    }//GEN-LAST:event_rbRown10MouseClicked

    /**
    * @param args the command line arguments
    */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblRownWynik;
    private javax.swing.JLabel lblSzerWynik;
    private javax.swing.JRadioButton rbRown10;
    private javax.swing.JRadioButton rbRown2;
    private javax.swing.JRadioButton rbRown3;
    private javax.swing.JRadioButton rbRown4;
    private javax.swing.JRadioButton rbRown5;
    private javax.swing.JRadioButton rbRown6;
    private javax.swing.JRadioButton rbRown7;
    private javax.swing.JRadioButton rbRown8;
    private javax.swing.JRadioButton rbRown9;
    private javax.swing.JRadioButton rbSzer10;
    private javax.swing.JRadioButton rbSzer2;
    private javax.swing.JRadioButton rbSzer3;
    private javax.swing.JRadioButton rbSzer4;
    private javax.swing.JRadioButton rbSzer5;
    private javax.swing.JRadioButton rbSzer6;
    private javax.swing.JRadioButton rbSzer7;
    private javax.swing.JRadioButton rbSzer8;
    private javax.swing.JRadioButton rbSzer9;
    private javax.swing.JTextField txtRown1;
    private javax.swing.JTextField txtRown10;
    private javax.swing.JTextField txtRown2;
    private javax.swing.JTextField txtRown3;
    private javax.swing.JTextField txtRown4;
    private javax.swing.JTextField txtRown5;
    private javax.swing.JTextField txtRown6;
    private javax.swing.JTextField txtRown7;
    private javax.swing.JTextField txtRown8;
    private javax.swing.JTextField txtRown9;
    private javax.swing.JTextField txtSzer1;
    private javax.swing.JTextField txtSzer10;
    private javax.swing.JTextField txtSzer2;
    private javax.swing.JTextField txtSzer3;
    private javax.swing.JTextField txtSzer4;
    private javax.swing.JTextField txtSzer5;
    private javax.swing.JTextField txtSzer6;
    private javax.swing.JTextField txtSzer7;
    private javax.swing.JTextField txtSzer8;
    private javax.swing.JTextField txtSzer9;
    // End of variables declaration//GEN-END:variables

}
