package pl.sperka.ae2.plugin.oldclasses.circuits;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kapitan
 */
import javax.swing.*;
import java.awt.*;
import java.net.URL;

public class OPampy extends javax.swing.JFrame {

    /**
     * Creates new form OPampy
     */
    public OPampy( Component parent ) {
        initComponents();
        URL imgURL1 = getClass().getClassLoader().getResource("pl/sperka/ae2/plugin/oldclasses/images/oanieodwr.jpg");
        ImageIcon icon1 = new ImageIcon(imgURL1);
        JLabel label1 = new JLabel(icon1);
        label1.setSize(200, 141);
        jpPict1.add(label1);
        label1.repaint();
        
        URL imgURL2 = getClass().getClassLoader().getResource("pl/sperka/ae2/plugin/oldclasses/images/oaodwr.jpg");
        ImageIcon icon2 = new ImageIcon(imgURL2);
        JLabel label2 = new JLabel(icon2);
        label2.setSize(200, 149);
        jpPict2.add(label2);
        label2.repaint();

        setLocationRelativeTo( parent );
    }
    
    private void liczNodwr()
    {
        java.text.NumberFormat nf = java.text.NumberFormat.getInstance();
        try {
        if(!jtR1no.getText().isEmpty()&&!jtWzno.getText().isEmpty())
        {
            double R1=nf.parse(jtR1no.getText()).doubleValue();
            double Wz=nf.parse(jtWzno.getText()).doubleValue();
            double R2=R1*(Wz-1);
            jlR2no.setText("R2 = "+nf.format(R2) +" om");
        }
        } catch(Exception e) {}
    }
    
    private void liczOdwr()
    {
        java.text.NumberFormat nf = java.text.NumberFormat.getInstance();
        try {
        if(!jtR1od.getText().isEmpty()&&!jtWzod.getText().isEmpty())
        {
            double R1=nf.parse(jtR1od.getText()).doubleValue();
            double Wz=nf.parse(jtWzod.getText()).doubleValue();
            double R2=-1*Wz*R1;
            jlR2od.setText("R2 = "+nf.format(R2) +" om");
        }
        } catch(Exception e) {}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jpPict2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtR1od = new javax.swing.JTextField();
        jtWzod = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jlR2od = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jpPict1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtR1no = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtWzno = new javax.swing.JTextField();
        jlR2no = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Wzmacniacze operacyjne");
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jpPict2Layout = new javax.swing.GroupLayout(jpPict2);
        jpPict2.setLayout(jpPict2Layout);
        jpPict2Layout.setHorizontalGroup(
            jpPict2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 201, Short.MAX_VALUE)
        );
        jpPict2Layout.setVerticalGroup(
            jpPict2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("R1");

        jtR1od.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtR1od.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtR1odKeyReleased(evt);
            }
        });

        jtWzod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtWzod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtWzodKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Wzmocnienie");

        jlR2od.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jpPict2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtR1od))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtWzod, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlR2od))
                .addGap(0, 178, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpPict2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtR1od, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtWzod, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlR2od, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Wzm. odwracający", jPanel2);

        javax.swing.GroupLayout jpPict1Layout = new javax.swing.GroupLayout(jpPict1);
        jpPict1.setLayout(jpPict1Layout);
        jpPict1Layout.setHorizontalGroup(
            jpPict1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 201, Short.MAX_VALUE)
        );
        jpPict1Layout.setVerticalGroup(
            jpPict1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("R1");

        jtR1no.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtR1no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtR1noKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Wzmocnienie");

        jtWzno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtWzno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtWznoKeyReleased(evt);
            }
        });

        jlR2no.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpPict1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtR1no))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtWzno, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlR2no))
                .addGap(0, 178, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpPict1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtR1no, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtWzno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlR2no, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Wzm. nieodwracający", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtR1noKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtR1noKeyReleased
        liczNodwr();
    }//GEN-LAST:event_jtR1noKeyReleased

    private void jtWznoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtWznoKeyReleased
        liczNodwr();
    }//GEN-LAST:event_jtWznoKeyReleased

    private void jtR1odKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtR1odKeyReleased
        liczOdwr();
    }//GEN-LAST:event_jtR1odKeyReleased

    private void jtWzodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtWzodKeyReleased
        liczOdwr();
    }//GEN-LAST:event_jtWzodKeyReleased

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jlR2no;
    private javax.swing.JLabel jlR2od;
    private javax.swing.JPanel jpPict1;
    private javax.swing.JPanel jpPict2;
    private javax.swing.JTextField jtR1no;
    private javax.swing.JTextField jtR1od;
    private javax.swing.JTextField jtWzno;
    private javax.swing.JTextField jtWzod;
    // End of variables declaration//GEN-END:variables
}
